version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow       # Change this to 'airflow'
      POSTGRES_PASSWORD: Udayuday9100
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:2.3.0
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:Udayuday9100@postgres/airflow
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
    ports:
      - "8080:8080"
    command: ["webserver"]

  airflow_scheduler:
    image: apache/airflow:2.3.0
    restart: always
    depends_on:
      - postgres
    command: ["scheduler"]
